### ISSUE TITLE
Run Test doesn't work when  try to run a single scenario

### ISSUE THREAD

**Issue by cchuyc** [Balrog994/cucumber-test-runner#13]
When I Click Run Test to try to run a single scenario.
I see a record was generated at the terminal (see the screenshot)
there is no pass or failed mark with the step. Seems nothing happend.

I clicked the Show Result Output. But there is nothing to show.
![image](https://github.com/Balrog994/cucumber-test-runner/assets/145535829/bb6d426a-ac39-4ec3-8c37-4c40f8b86291)

![40740379883bbacd5936c6756ec4182](https://github.com/Balrog994/cucumber-test-runner/assets/145535829/2d750eff-f0c2-4ae2-9294-e14955dec6a8)

here is my cucumber.js configuration

![image](https://github.com/Balrog994/cucumber-test-runner/assets/145535829/d4200d34-6c53-4a3f-a847-5b2180974bba)

**Comment by Balrog994** [comment]
Hi @cchuyc ,

have you tried looking at the "Cucumber Test Runner" output window and see if there are any errors?

By looking at your configuration file, it seems like you have some more configuration options that are not visible in the screenshot. Please ensure that no `path` is specified in the options used by the test runner, it usually break the runner because of a bug in `cucumber-cli`.

You can follow the guide in `README` to configure a custom profile just for the runner ;)

**Comment by cchuyc** [comment]
Thank you @Balrog994 ,the problem was solved after the cucumberTestRunner.profile was configured correctly.
